spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tiger
    url: jdbc:mysql://http.localhost:3306/mydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

